### ISSUE TITLE
GA: _calc_fitness_function() can return very large values which cause Overflow

### ISSUE THREAD

**Issue by Gabriel-p** [annoviko/pyclustering#597] opened 2020-04-30 14:45 UTC
I'm getting fitness values over 10000 for example, which cause the `_select()` function to overflow [here](https://github.com/annoviko/pyclustering/blob/78338b698ce8c3d318be7326a30aedf1a4db216e/pyclustering/cluster/ga.py#L522):

            fitness[_idx] = math.exp(1 + fitness[_idx] * select_coeff)

Perhaps clip the `fitness` array before exponentiating?

    fitness = np.clip(fitness, a_min=None, a_max=100)

**Comment by annoviko** [comment] 2020-04-30 16:39
Hi, @Gabriel-p 

Thank you for the reporting, the correction for the problem will be introduced.

**Comment by Gabriel-p** [comment] 2020-04-30 18:38
Quick question @annoviko (not really related to this issue): how do you obtain the labels once the GA is processed? The `get_clusters()` method returns what I believe are the indexes that point to the *centers* for each found cluster, but there appears to be no method for assigning labels to the data (something like the `predict()` method in kmeans)?

**Comment by annoviko** [comment] 2020-10-28 12:19
As I understand, the cause of the problem is non-normalized data. I would suggest to normalize data between `[0, 1]` to perform cluster analysis using genetic algorithm, for example, using the same approach as you suggested for the fitness function.

Nevertheless, I have added human-readable error that explains how to resolve the issue.

**Closed** 2020-10-28 12:46 UTC
Labels: Bug
